### ISSUE TITLE
rhacct --report $email results in HTTP Error 502: Bad Gateway from call to user_details(email)

### ISSUE THREAD

**Issue by fultonj** [fultonj/rhacct#1]
```
$ rhacct -r johfulto@redhat.com
Traceback (most recent call last):
  File "/home/jfulton/bin/rhacct", line 944, in ?
    user_details(email)
  File "/home/jfulton/bin/rhacct", line 321, in user_details
    response = urllib2.urlopen(req)  
  File "/usr/lib64/python2.4/urllib2.py", line 130, in urlopen
    return _opener.open(url, data)
  File "/usr/lib64/python2.4/urllib2.py", line 364, in open
    response = meth(req, response)
  File "/usr/lib64/python2.4/urllib2.py", line 471, in http_response
    response = self.parent.error(
  File "/usr/lib64/python2.4/urllib2.py", line 396, in error
    result = self._call_chain(*args)
  File "/usr/lib64/python2.4/urllib2.py", line 337, in _call_chain
    result = func(*args)
  File "/usr/lib64/python2.4/urllib2.py", line 827, in http_error_401
    host, req, headers)
  File "/usr/lib64/python2.4/urllib2.py", line 806, in http_error_auth_reqed
    return self.retry_http_basic_auth(host, req, realm)
  File "/usr/lib64/python2.4/urllib2.py", line 816, in retry_http_basic_auth
    return self.parent.open(req)
  File "/usr/lib64/python2.4/urllib2.py", line 364, in open
    response = meth(req, response)
  File "/usr/lib64/python2.4/urllib2.py", line 471, in http_response
    response = self.parent.error(
  File "/usr/lib64/python2.4/urllib2.py", line 402, in error
    return self._call_chain(*args)
  File "/usr/lib64/python2.4/urllib2.py", line 337, in _call_chain
    result = func(*args)
  File "/usr/lib64/python2.4/urllib2.py", line 480, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 502: Bad Gateway
$ 
```

**Comment by fultonj** [comment]
This bug might be related to the following:
- https://bugzilla.redhat.com/show_bug.cgi?id=894402
- https://bugzilla.redhat.com/show_bug.cgi?id=1122294

**Comment by fultonj** [comment]
This happens VERY rarely. I ran this on our QA instance and only 2 names produced this error while the reaming 81 were fine (42 of which had usernames that were email addresses). The two problem names were my own dummy users jfulton{4,5}@redhat.com created when I tested the rhacct with -c. I am going to look closer at those dummy users as I don't think the --report feature is the problem. 

rhacct -l > all.txt
cat all.txt | awk {'print $1'} | sed s/,//g > names.txt 
for x in `cat names.txt`; do echo "rhacct -r $x"; rhacct -r $x; echo "-----------"; done > unit_test.txt

**Comment by fultonj** [comment]
The two dummy users came from these commands. 

```
rhacct -v -c jfulton5@redhat.com -f John -s Fulton -p cases
rhacct -v -c jfulton4@redhat.com -f John -s Fulton -p cases
```

I can create other users without any problems however. 

[jfulton@rhel5 ~]$ rhacct -v -c jfulton6 -f John -s Fulton 
warning: creating jfulton6 without any permissions
Creating John Fulton (jfulton6) with the permissions: 
HTTP return:  HTTP 201: Created
Created user jfulton6 with user_id: 7316382
error: failed to create: jfulton6
[jfulton@rhel5 ~]$ rhacct -r jfulton6
first: John
last: Fulton
email: jfulton6
phone: 555-555-1212
created: 2014-08-04T20:22:47Z
permissions: cases,subscritions,downloads,systems,
[jfulton@rhel5 ~]$ 

As you can see I can create and report on this new user. 

By the way the no permissions "warning" can be ignored (though I need to clean this up) as he gets the default permissions. 
                    if len(options.permissions) is 0:
                        if options.verbose:
                            print "warning: creating "+email+" without any permission

The other error message (that I need to fix) simply came from this line:
                    if not create_user(email, options.first, options.last, \
                                       permissions, options.verbose):
                        sys.exit("error: failed to create: "+email)

which I have returning false since it doesn't set the roles yet directly and thus anyone created gets the defaults (cases,subscritions,downloads,systems). I still just have my app returning False so I need to adjust that too. 

```
   # 2. Get user ID
    user_id = get_user_id_number(email)
    if verbose:
        print "Created user " + email,
        print "with user_id: " + str(user_id) 
    # 3. Update roles (aka permissions for now)
    # unless specified the default permissions are
    # cases,subscritions,downloads,systems
    # todo: HERE

return False
```

However, that's outside the scope of this problem.

**Comment by fultonj** [comment]
I am going to close this for now and chock it up to a problem with those two users. I may re-open if I run into it again however.
